#!/usr/bin/zsh
# vi-keys, but with bindings to make it more intuitive for emacs people:
bindkey -v
bindkey "^P" up-line-or-history
bindkey "^N" down-line-or-history
bindkey "^K" vi-change-eol
bindkey "^R" history-incremental-search-backward

# Add the local compfuncs directory for other completion libraries like _git
fpath=( $HOME/.zsh/compfuncs $fpath )

# Semi-voodoo, but enables <Esc>v to use vim to edit a command:
autoload edit-command-line; zle -N edit-command-line
autoload -U compinit; compinit
bindkey -M vicmd v edit-command-line

# Load the git prompt theme system
autoload -U promptinit
promptinit

fignore=(.o \~ .swp CVS .git)
zmodload zsh/complist

zstyle ':completion:*' list-colors ''
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' squeeze-slashes true

alias find='noglob find'
